pom.xml
src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/has-item-tests.eo

introduce .has-item object

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/has-item-tests.eo

introduce .has-items object

---

pom.xml
src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/arrays-matchers-tests.eo

introduce .array-each object

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/all-of-tests.eo
src/test/eo/org/eolang/hamcrest/any-of-tests.eo
src/test/eo/org/eolang/hamcrest/described-as-tests.eo

all-of and any-of didn't work properly

---

examples/all-of-tests.eo
examples/any-of-tests.eo
examples/anything-tests.eo
examples/arrays-matchers-tests.eo
examples/close-to-tests.eo
examples/described-as-tests.eo
examples/equal-to-tests.eo
examples/greater-than-tests.eo
examples/is-tests.eo
examples/less-than-tests.eo
examples/not-tests.eo
src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/all-of-tests.eo
src/test/eo/org/eolang/hamcrest/any-of-tests.eo
src/test/eo/org/eolang/hamcrest/anything-tests.eo
src/test/eo/org/eolang/hamcrest/arrays-matchers-tests.eo
src/test/eo/org/eolang/hamcrest/close-to-tests.eo
src/test/eo/org/eolang/hamcrest/described-as-tests.eo
src/test/eo/org/eolang/hamcrest/equal-to-tests.eo
src/test/eo/org/eolang/hamcrest/greater-than-tests.eo
src/test/eo/org/eolang/hamcrest/is-tests.eo
src/test/eo/org/eolang/hamcrest/less-than-tests.eo
src/test/eo/org/eolang/hamcrest/not-tests.eo

 +home and +version metas in all files

---

LICENSE.txt
pom.xml
src/main/java/EOorg.EOeolang.EOhamcrest/package-info.java

add package-info.java

---

pom.xml
src/main/eo/org/eolang/hamcrest/assert-that.eo

new interface of "memory"

---

README.md
examples/all-of-tests.eo
examples/any-of-tests.eo
examples/anything-tests.eo
examples/described-as-tests.eo
examples/equal-to-tests.eo
examples/greater-than-tests.eo
examples/is-tests.eo
examples/less-than-tests.eo
examples/not-tests.eo
pom.xml
src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/all-of-tests.eo
src/test/eo/org/eolang/hamcrest/any-of-tests.eo
src/test/eo/org/eolang/hamcrest/anything-tests.eo
src/test/eo/org/eolang/hamcrest/described-as-tests.eo
src/test/eo/org/eolang/hamcrest/equal-to-tests.eo
src/test/eo/org/eolang/hamcrest/greater-than-tests.eo
src/test/eo/org/eolang/hamcrest/is-tests.eo
src/test/eo/org/eolang/hamcrest/less-than-tests.eo
src/test/eo/org/eolang/hamcrest/not-tests.eo

upgrade to 0.23.11

---

.rultor.yml

version up to 0.23.15 (add maven opts)

---

pom.xml
src/main/eo/org/eolang/hamcrest/assert-that.eo

version up to 0.23.17

---

pom.xml

exclude duplicate error checks

exclude duplicate error checks

---

pom.xml

This will be helpful. Please, merge and then release a new version.

restrict release binaries

---

src/test/eo/org/eolang/hamcrest/not-tests.eo

add test to compare different strings

---

pom.xml
src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/failed-output/equal-to-failed-message.eo

Closes: #98
I convert test's actual value to constant. We shouldn't dataize it several times since now.

made actual value dataized only once

---

src/test/eo/org/eolang/hamcrest/failed-output/all-of-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/any-of-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/anything-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/arrays-matchers-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/close-to-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/described-as-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/equal-to-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/greater-than-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/is-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/less-than-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/not-failed-output.eo

adds failed output checks

---

src/test/eo/org/eolang/hamcrest/failed-output/described-as-failed-output.eo

#107: added tests for described-as failure

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/failed-output/close-to-failed-output.eo

#105: added close-to-failed-output tests

---

src/test/eo/org/eolang/hamcrest/failed-output/all-of-failed-output.eo

#108: added all-of fail output

---

src/test/eo/org/eolang/hamcrest/failed-output/any-of-failed-output.eo

added failed test for any-of

---

src/test/eo/org/eolang/hamcrest/failed-output/is-failed-output.eo

added failed test for is

---

src/test/eo/org/eolang/hamcrest/failed-output/not-failed-output.eo

added failed test for not

---

src/test/eo/org/eolang/hamcrest/failed-output/anything-failed-output.eo

added test for anything matcher

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/test/eo/org/eolang/hamcrest/contains-string-tests.eo

contains-string

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/anything-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/equal-to-matcher.eo

move anything and equal-to matchers

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/all-of-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/not-matcher.eo

moved all-of and not matchers

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/any-of-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/greater-than-matcher.eo

moved any-of and greater-than matchers

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/close-to-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/less-than-matcher.eo

moved close-to and less-than matchers

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/described-as-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/is-matcher.eo

moved described-as and is matchers

---

.github/workflows/codecov.yml
src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/has-item-matcher.eo

moved has-item matcher and fixed described-as

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/has-items-matcher.eo

moved has-items matcher

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/array-each-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/has-items-matcher.eo

moved array-each matcher

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/contains-string-matcher.eo

moved contains-string matcher

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/string-ends-with-matcher.eo
src/test/eo/org/eolang/hamcrest/failed-output/any-of-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/string-ends-with-failed-output.eo
src/test/eo/org/eolang/hamcrest/string-ends-with-tests.eo

added string-ends-with matcher

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/string-starts-with-matcher.eo
src/test/eo/org/eolang/hamcrest/failed-output/string-starts-with-failed-output.eo
src/test/eo/org/eolang/hamcrest/string-starts-with-tests.eo

 implemented string-starts-with matcher

---

renovate.json

dependency ignored

---

pom.xml

stack size increased up to 256 Mb

---

src/main/eo/org/eolang/hamcrest/assert-that.eo
src/main/eo/org/eolang/hamcrest/matchers/blank-string-matcher.eo
src/test/eo/org/eolang/hamcrest/blank-string-tests.eo
src/test/eo/org/eolang/hamcrest/failed-output/blank-string-failed-output.eo

added blank-string matcher

---

src/main/eo/org/eolang/hamcrest/assert-twice-that.eo
src/test/eo/org/eolang/hamcrest/all-of-tests.eo
src/test/eo/org/eolang/hamcrest/equal-to-tests.eo
src/test/eo/org/eolang/hamcrest/failed-output/all-of-failed-output.eo
src/test/eo/org/eolang/hamcrest/failed-output/equal-to-failed-output.eo

Closes: #167 
What is done:
- added new `assert-twice-that` object
- added several tests
- added several todos

introduced assert-twice-that object

---

pom.xml

added eo-runtime

---

src/main/eo/org/eolang/hamcrest/matchers/all-of-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/any-of-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/anything-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/array-each-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/blank-string-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/close-to-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/contains-string-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/described-as-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/empty-string-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/equal-to-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/greater-than-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/is-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/is-substring-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/less-than-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/matches-regex-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/not-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/string-ends-with-matcher.eo
src/main/eo/org/eolang/hamcrest/matchers/string-starts-with-matcher.eo

#189 adjust for new syntax

---

pom.xml

EO version has changed to 0.29.1
